apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{PROJECT_NAME}}
spec:
  type: {{SERVICE_TYPE}}
  selector:
    app: {{PROJECT_NAME}}
  ports:
    - name: http
      port: {{PORT}}
      targetPort: {{PORT}}
