# Generated by CloudForge — no Dockerfile was present in the cloned repo.
# For a Node.js project detected via package.json.
FROM node:20-alpine

WORKDIR /app

# Install dependencies first for better layer caching.
COPY package*.json ./
RUN npm install --omit=dev

# Copy the rest of the app.
COPY . .

# Heroku-style start; override via CMD if the app needs a custom command.
CMD ["npm", "start"]
