# Generated by CloudForge — no Dockerfile was present in the cloned repo.
# For a Python project detected via requirements.txt.
FROM python:3.12-slim

WORKDIR /app

# Install dependencies first for better layer caching.
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app.
COPY . .

# Adjust the module path if the app entrypoint differs.
CMD ["python", "app.py"]
